org.gradle.jvmargs = -Xmx4096M
org.gradle.daemon = false

# Mc stuff
minecraft_version = 26.2
minecraft_required = ~26.2
minecraft_supported_versions=26.2
minecraft_major_version = 26.2

# Mod stuff
mod_id = farmersdelight
mod_name = Farmer's Delight
mod_version = 3.6.26
mod_license = MIT License
mod_group_id = vectorwing
mod_authors = MehVahdJukaar, ChrysanthCow, cassiancc
mod_description = A cozy expansion to farming and cooking!
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated
mod_github = https://github.com/MehVahdJukaar/FarmersDelightRefabricated
mod_credits = vectorwing, drexhd, moriyashiine

curseforge_project_id = 993166
modrinth_project_id = 7vxePowz

# Loaders
fabric_loader_version = 0.19.3
fabric_api_version = 0.157.0+26.2

# Other deps
fabric_asm_version = v2.3
jei_version = 29.5.0.26
rei_version = 26.2.820
emi_version = 1.1.12+1.21
rrv_version = 8.8.0+26.2
appleskin_version = mc26.2-3.0.10
crafttweaker_version = 21.0.2
crafttweaker_ap_version = 3.0.0.15
modmenu_version = 20.0.1
yacl_version=3.9.6+26.2-fabric

cloth_version = 26.2.155
